export const endpoints = {
    BaseUrl: 'https://healthsyshub.service.azurewebsites.bdprasad.in/api',
    UrlConstants: {
        Authenticate: 'Account/AuthenticateUserAsync',
        VerifyAccesToken: 'Account/VerifyAccesToken',
        ActivateOrInActivateUserAsync: 'Account/ActivateOrInActivateUserAsync',
        ResetPasswordAsync: 'Account/ResetPasswordAsync',
        ForgotPasswordAsync: 'Account/ForgotPasswordAsync',
        GenerateUserCliams: 'Account/GenarateUserClaimsAsync',
        GetHospitalInformationsAsync: 'Hospital/GetHospitalInformationsAsync',
        GetHospitalInformationByIdAsync: 'Hospital/GetHospitalInformationByIdAsync',
        GetPharmacyByIdAsync: 'Pharmacy/GetPharmacyByIdAsync',
        InsertOrUpdatePharmacyAsync: 'Pharmacy/InsertOrUpdatePharmacyAsync',
        GetPharmacyMedicineByPharmacyAsync: 'PharmacyMedicine/GetPharmacyMedicineAsync',
        GetPharmacyMedicineByMedicineIdAsync: 'PharmacyMedicine/GetPharmacyMedicineByMedicineIdAsync',
        InsertOrUpdatePharmacyMedicineAsync: 'PharmacyMedicine/InsertOrUpdatePharmacyMedicineAsync',
        GetPharmacyStaffAsync: 'PharmacyStaff/GetPharmacyStaffAsync',
        InsertOrUpdatePharmacyStaffAsync: 'PharmacyStaff/InsertOrUpdatePharmacyStaffAsync',
        GetPharmacyStaffByIdAsync: 'PharmacyStaff/GetPharmacyStaffByIdAsync',
        GetPharmacyStaffsAsync: 'PharmacyStaff/GetPharmacyStaffsAsync',
        GetPharmacyStaffByharmacyAsync: 'PharmacyStaff/GetPharmacyStaffByharmacyAsync',
        GetPharmacyOrderRequestsByPharmacyAsync: "PharmacyOrderRequest/GetPharmacyOrderRequestsByPharmacyAsync",
        GetPharmacyOrderRequestsByHospitalAsync: 'PharmacyOrderRequest/GetPharmacyOrderRequestsByHospitalAsync',
        GetPharmacyOrderRequestsByPatientAsync: 'PharmacyOrderRequest/GetPharmacyOrderRequestsByPatientAsync',
        GetPharmacyOrderRequestDetailAsync: 'PharmacyOrderRequest/GetPharmacyOrderRequestDetailAsync',
        InsertOrUpdatePharmacyOrderRequestAsync: 'PharmacyOrderRequest/InsertOrUpdatePharmacyOrderRequestAsync',
        ProcessPharmacyOrderRequestAsync: 'PharmacyOrderRequest/ProcessPharmacyOrderRequestAsync',
        Tickets: 'Tickets',
        MyTickets: 'Tickets/GetAllUserTickets',
        PriorityType: 'PriorityTypes',
        Order: 'Order',
        OrdersByUser: 'Order/GetAllOrdersByUser',
        PlaceOrder: 'Order/ProcessOrder',
        HandleOrderPayment: 'Order/HandleOrderPayment',
        HandleOrderProcess: 'Order/HandleOrderProcess',
        fetchCancelledOrders: 'Order/fetchCancelledOrders',
        fetchRejectedOrders: 'Order/fetchRejectedOrders ',
        fetchRefundedOrders: 'Order/fetchRefundedOrders',
        fetchDeleveredOrders: 'Order/fetchDeleveredOrders',
        fetchInTrasitOrders: 'Order/fetchInTrasitOrders',
        fetchUserSpecificOrders: 'Order/fetchUserSpecificOrders',
        PrivacyPolicy: 'PrivacyPolicy',
        RefundAndExchange: 'RefundAndExchange',
        Refund: 'Refund',
        CancelationPolicy: 'CancelationPolicy',
        TermsAndConditions: 'TermsAndConditions',
        TermsOfUses: 'TermsOfUses',
        fetchUserSpecificPayment: 'Payments/fetchUserSpecificPayment',
        ChangePasswordAsync: 'User/ChangePasswordAsync',
        ProfileUpdateRequestAsync: 'User/ProfileUpdateRequestAsync',
        GetPharmacyOrdersListByPharmacyAsync: 'Order/GetPharmacyOrdersListByPharmacyAsync',
        ProcessPharmacyOrderPaymentAsync: 'PharmacyPayment/ProcessPharmacyOrderPaymentAsync',
        GetPharmacyPaymentListAsync: 'PharmacyPayment/GetPharmacyPaymentListAsync',
        GetPharmacyPaymentDetailAsync: 'PharmacyPayment/GetPharmacyPaymentDetailAsync',
        GetInPatientsAsync: 'InPatient/GetInPatientsAsync',
        GetActiveInPatientsAsync: 'InPatient/GetActiveInPatientsAsync',
        GetInPatientByIdAsync: 'InPatient/GetInPatientByIdAsync',
        InsertOrUpdateInpatientAsync: 'InPatient/InsertOrUpdateInpatientAsync',
        DeleteInpatientAsync: 'InPatient/DeleteInpatientAsync',
        GetInpatientsByStatusAsync: 'InPatient/GetInpatientsByStatusAsync',
        GetAllAdmissionsAsync: 'InPatientAdmission/GetAllAdmissionsAsync',
        GetActiveAdmissionsAsync: 'InPatientAdmission/GetActiveAdmissionsAsync',
        GetAdmissionByIdAsync: 'InPatientAdmission/GetAdmissionByIdAsync',
        InsertOrUpdateAdmissionAsync: 'InPatientAdmission/InsertOrUpdateAdmissionAsync',
        GetAdmissionsByPatientIdAsync: 'InPatientAdmission/GetAdmissionsByPatientIdAsync',
        GetAdmissionsByHofspitalIdAsync: 'InPatientAdmission/GetAdmissionsByHospitalIdAsync',
        GetMostRecentAdmissionAsync: 'InPatientAdmission/GetMostRecentAdmissionAsync',
        GetBedAssignmentsAsync: 'BedAssignment/GetBedAssignmentsAsync',
        GetActiveBedAssignmentsAsync: 'BedAssignment/GetActiveBedAssignmentsAsync',
        GetBedAssignmentByIdAsync: 'BedAssignment/GetBedAssignmentByIdAsync',
        GetBedAssignmentsByAdmissionIdAsync: 'BedAssignment/GetBedAssignmentsByAdmissionIdAsync',
        InsertOrUpdateBedAssignmentAsync: 'BedAssignment/InsertOrUpdateBedAssignmentAsync',
        GetBedAssignmentsByStatusAsync: 'BedAssignment/GetBedAssignmentsByStatusAsync',
        GetBedAssignmentsByWardIdAsync: 'BedAssignment/GetBedAssignmentsByWardIdAsync',
        GetBedAssignmentsByDateRangeAsync: 'BedAssignment/GetBedAssignmentsByDateRangeAsync',
        GetMostRecentBedAssignmentAsync: 'BedAssignment/GetMostRecentBedAssignmentAsync',
        GetAllMedicationsAsync: 'InPatientMedication/GetAllMedicationsAsync',
        GetActiveMedicationsAsync: 'InPatientMedication/GetActiveMedicationsAsync',
        GetMedicationByIdAsync: 'InPatientMedication/GetMedicationByIdAsync',
        InsertOrUpdateMedicationAsync: 'InPatientMedication/InsertOrUpdateMedicationAsync',
        DeleteMedicationAsync: 'InPatientMedication/DeleteMedicationAsync',
        GetMedicationsByInpatientIdAsync: 'InPatientMedication/GetMedicationsByInpatientIdAsync',
        GetMedicationsByDoctorIdAsync: 'InPatientMedication/GetMedicationsByDoctorIdAsync',
        GetMostRecentMedicationAsync: 'InPatientMedication/GetMostRecentMedicationAsync',
        GetAllTreatmentPlansAsync: 'InPatientTreatmentPlan/GetAllTreatmentPlansAsync',
        GetActiveTreatmentPlansAsync: 'InPatientTreatmentPlan/GetActiveTreatmentPlansAsync',
        GetTreatmentPlanByIdAsync: 'InPatientTreatmentPlan/GetTreatmentPlanByIdAsync',
        InsertOrUpdateTreatmentPlanAsync: 'InPatientTreatmentPlan/InsertOrUpdateTreatmentPlanAsync',
        DeleteTreatmentPlanAsync: 'InPatientTreatmentPlan/DeleteTreatmentPlanAsync',
        GetTreatmentPlansByInpatientIdAsync: 'InPatientTreatmentPlan/GetTreatmentPlansByInpatientIdAsync',
        GetTreatmentPlansByDoctorIdAsync: 'InPatientTreatmentPlan/GetTreatmentPlansByDoctorIdAsync',
        GetTreatmentPlansByStatusAsync: 'InPatientTreatmentPlan/GetTreatmentPlansByStatusAsync',
        GetAllVitalSignsAsync: 'InPatientVitalSigns/GetAllVitalSignsAsync',
        GetVitalSignsByInpatientIdAsync: 'InPatientVitalSigns/GetVitalSignsByInpatientIdAsync',
        GetVitalSignByIdAsync: 'InPatientVitalSigns/GetVitalSignByIdAsync',
        InsertOrUpdateVitalSignAsync: 'InPatientVitalSigns/InsertOrUpdateVitalSignAsync',
        DeleteVitalSignAsync: 'InPatientVitalSigns/DeleteVitalSignAsync',
        GetAllBeds: 'WardBed/GetAllBeds',
        GetActiveBeds: 'WardBed/GetActiveBeds',
        GetBedById: 'WardBed/GetBedById',
        GetBedsByWard: 'WardBed/GetBedsByWard',
        GetBedsByStatus: 'WardBed/GetBedsByStatus',
        GetBedsByType: 'WardBed/GetBedsByType',
        CreateOrUpdateBed: 'WardBed/CreateOrUpdateBed',
        DeleteBed: 'WardBed/DeleteBed',
        GetBedCountByWard: 'WardBed/GetBedCountByWard',
        GetAvailableBedsCount: 'WardBed/GetAvailableBedsCount',
        GetAllWardsAsync: 'Ward/GetAllWardsAsync',
        GetActiveWardsAsync: 'Ward/GetActiveWardsAsync',
        GetWardByIdAsync: 'Ward/GetWardByIdAsync',
        GetWardsByHospitalIdAsync: 'Ward/GetWardsByHospitalIdAsync',
        InsertOrUpdateWardAsync: 'Ward/InsertOrUpdateWardAsync',
        DeleteWardAsync: 'Ward/DeleteWardAsync',
        GetAllConsultationsAsync: 'Consultation/GetAllConsultationsAsync',
        GetConsultationByAppointmentIdAsync: 'Consultation/GetConsultationByAppointmentIdAsync',
        GetConsultationByConsultationIdAsync: 'Consultation/GetConsultationByConsultationIdAsync',
        GetConsultationsByDoctorAsync: 'Consultation/GetConsultationsByDoctorAsync',
        GetConsultationsByHospitalAsync: 'Consultation/GetConsultationsByHospitalAsync',
        InsertOrUpdateConsultationDetailsAsync: 'Consultation/InsertOrUpdateConsultationDetailsAsync',
        GetDoctorAppointmentsAsync: 'DoctorAppointment/GetDoctorAppointmentsAsync',
        GetDoctorAppointmentByIdAsync: 'DoctorAppointment/GetDoctorAppointmentByIdAsync',
        InsertOrUpdateDoctorAppointment: 'DoctorAppointment/InsertOrUpdateDoctorAppointment',
        DeleteDoctorAppointmentAsync: 'DoctorAppointment/DeleteDoctorAppointmentAsync',
        GetActiveDoctorAppointmentsAsync: 'DoctorAppointment/GetActiveDoctorAppointmentsAsync',
        GetDoctorAppointmentsByDoctorAsync: 'DoctorAppointment/GetDoctorAppointmentsByDoctorAsync',
        GetDoctorAppointmentsByPatientAsync: 'DoctorAppointment/GetDoctorAppointmentsByPatientAsync',
        GetDoctorAppointmentsByPhoneAsync: 'DoctorAppointment/GetDoctorAppointmentsByPhoneAsync',
        GetDoctorAppointmentsByDateRangeAsync: 'DoctorAppointment/GetDoctorAppointmentsByDateRangeAsync',
        GenerateTokenNumberAsync: 'DoctorAppointment/GenerateTokenNumberAsync',
        GetDoctorAppointmentDetailsAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsAsync',
        GetDoctorAppointmentDetailsByDoctorAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsByDoctorAsync',
        GetDoctorAppointmentDetailsByPatientAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsByPatientAsync',
        GetDoctorAppointmentDetailsByIdAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsByIdAsync',
        GetActiveDoctorAppointmentDetailsAsync: 'DoctorAppointment/GetActiveDoctorAppointmentDetailsAsync',
        GetDoctorAppointmentDetailsByDateRangeAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsByDateRangeAsync',
        GetDoctorAppointmentDetailsByPhoneAsync: 'DoctorAppointment/GetDoctorAppointmentDetailsByPhoneAsync',
        GetAppointmentsReportAsync: 'DoctorAppointment/GetAppointmentsReportAsync',
        InsertOrUpdateDoctorAsync: 'Doctor/InsertOrUpdateDoctorAsync',
        GetDoctorByIdAsync: 'Doctor/GetDoctorByIdAsync',
        GetDoctorsByHospitalAsync: 'Doctor/GetDoctorsByHospitalAsync',
        GetHospitalsAsync: 'Hospital/GetHospitalsAsync',
        GetHospitalByIdAsync: 'Hospital/GetHospitalByIdAsync',
        InsertOrUpdateHospitalAsync: 'Hospital/InsertOrUpdateHospitalAsync',
        InsertOrUpdateHospitalContactInformationAsync: 'Hospital/InsertOrUpdateHospitalContactInformationAsync',
        InsertOrUpdateHospitalContentInformationAsync: 'Hospital/InsertOrUpdateHospitalContentInformationAsync',
        InsertOrUpdateHospitalDepartmentInformationAsync: 'Hospital/InsertOrUpdateHospitalDepartmentInformationAsync',
        InsertOrUpdateHospitalSpecialtyInformationAsync: 'Hospital/InsertOrUpdateHospitalSpecialtyInformationAsync',
        GetHospitalTypesAsync: 'HospitalType/GetHospitalTypesAsync',
        GetHospitalTypeByIdAsync: 'HospitalType/GetHospitalTypeByIdAsync',
        InsertOrUpdateHospitalType: 'HospitalType/InsertOrUpdateHospitalType',
        GetLabsAsync: 'Lab/GetLabsAsync',
        GetLabByIdAsync: 'Lab/GetLabByIdAsync',
        InsertOrUpdateLabAsync: 'Lab/InsertOrUpdateLabAsync',
        GetLabsBySearchStringAsync: 'Lab/GetLabsAsync',
        GetLabTestsAsync: 'LabTest/GetLabTestsAsync',
        GetLabTestByIdAsync: 'LabTest/GetLabTestByIdAsync',
        InsertOrUpdateLabTestAsync: 'LabTest/InsertOrUpdateLabTestAsync',
        GetMedicinesAsync: 'Medicine/GetMedicinesAsync',
        GetMedicineByIdAsync: 'Medicine/GetMedicineByIdAsync',
        InsertOrUpdateMedicineAsync: 'Medicine/InsertOrUpdateMedicineAsync',
        GetPharmacyOrderByIdAsync: 'Order/GetPharmacyOrderByIdAsync',
        ProcessPharmacyOrdersRequestAsync: 'Order/ProcessPharmacyOrdersRequestAsync',
        GetPatientTypesAsync: 'PatientType/GetPatientTypesAsync',
        GetPatientTypeByIdAsync: 'PatientType/GetPatientTypeByIdAsync',
        InsertOrUpdatePatientTypeAsync: 'PatientType/InsertOrUpdatePatientTypeAsync'
    },
    Messages: {
        InvalidPassword: "Authentication Failed due to Invalid Password ,Please enter correct password and try again",
        InValidUserName: "Authentication Failed due to Invalid UserName ,Please enter correct username and try again",
        UserWasBlocked: "User Was blocked",
        SomethingwentWrong: "Something went wrong,Please try after sometime"
    },
    Titles: {
        InvalidPassword: "Wrong/Invalid Password",
        InValidUserName: "Worng/Invalid Username",
        UserWasBlocked: "User blocked",
        SomethingWentWrong: "Something Went wrong"
    },
    ErrorCodes: {
        EC1001: 1001,
        EC1002: 1002,
        EC1003: 1003,
        EC1004: 1004
    },
    AppConstants: {
        Roles: {
            DigitalSalesMarketing: "Digital Sales Marketing",
            ProductManager: "Product Manager",
            CustomerServiceRepresentative: "Customer Service Representative",
            Customer: "Customer",
            Developer: "Developer",
            EcommerceManager: "E-commerce Manager",
            WebDeveloper: "Web Developer",
            OperationManager: "Operation Manager",
            GraphicDesigner: "Graphic Designer",
            DataAnalyst: "Data Analyst",
            FashionDesigner: "Fashion Designer",
            Administrator: "Administrator",
            SoftwareEngineer: "Software Engineer",
            User: "User",
            Executive: "Executive",
            Seller: "Seller",
        },
        departments: {
            Sales: "Sales",
        },
        FashionDesignerType: {
            ReadyToWear: "Ready-to-wear",
            EconomyFashion: "Economy fashion",
            HauteCouture: "Haute couture",
            TextileDesigner: "Textile Designer",
            FootwearDesigners: "Footwear designers",
            GraphicDesigner: "Graphic Designer",
            AccessoryDesigner: "Accessory designer",
            AthleticWear: "Athletic wear",
            FastFashion: "Fast fashion",
            MassMarketDesigners: "Mass market designers",
            KidswearDesigners: "Kidswear designers",
            FashionMarketer: "Fashion marketer",
            FashionWriter: "Fashion writer",
            LimitedEdition: "Limited edition",
            Merchandiser: "Merchandiser",
            SpecializedAreasOfFashionDesign: "Specialized areas of fashion design",
            Shirts: "Shirts",
            Jeans: "Jeans",
            Swimwear: "Swimwear",
            Sleepwear: "Sleepwear",
            Sportswear: "Sportswear",
            Jumpsuits: "Jumpsuits",
            Blazers: "Blazers",
            Jackets: "Jackets",
            Shoes: "Shoes",
            MensDresses: "Men's Dresses",
            WomensDresses: "Women's Dresses",
            BabysDresses: "Baby's Dresses",
        },
        Countries: {
            Afghanistan: "Afghanistan",
            Albania: "Albania",
            Algeria: "Algeria",
            Argentina: "Argentina",
            Australia: "Australia",
            Bangladesh: "Bangladesh",
            "USA": "United States of America",
            India: "India",
            Pakistan: "Pakistan",
            "People Republic of China": "People Republic of China",
            Singapore: "Singapore",
            Dubai: "Dubai",
            SaudiArabia: "Saudi Arabia",
            Bangkok: "Bangkok",
        },
        States: {
            TELANGANA: "Telangana",
            ANDHRAPRADESH: "Andhra Pradesh",
            KARNATAKA: "Karnataka",
            MAHARASTRA: "Maharashtra",
            UTTERPRADESH: "Uttar Pradesh",
            MADYAPRADESH: "Madhya Pradesh",
            TAMILNADU: "Tamil Nadu",
            KERALA: "Kerala",
            GOA: "Goa",
            ORISSA: "Odisha",
            PANJAB: "Punjab",
            SINDHU: "Sindh",
            Alabama: "Alabama",
            Alaska: "Alaska",
            Arizona: "Arizona",
            Arkansas: "Arkansas",
            California: "California",
            Colorado: "Colorado",
            Connecticut: "Connecticut",
            HARYANA: "Haryana",
            JAMMUKASHMIR: "Jammu & Kashmir",
            Srinagar: "Srinagar",
        },
        Cities: {
            HYDERABAD: "Hyderabad",
            WARANGAL: "Warangal",
            KARIMNAGAR: "Karimnagar",
            KHAMMAM: "Khammam",
            NIZAMABAD: "Nizamabad",
            MEDAK: "Medak",
            AMARAVATHI: "Amaravathi",
            VISHAKAPATNAM: "Vishakapatnam",
            THIRUPATHI: "Thirupathi",
            VijayaWada: "Vijayawada",
            California: "California",
            Bhadrachalam: "Bhadrachalam",
            Hanmakonda: "Hanmakonda",
            BhadraChalam1: "BhadraChalam1",
            BCM: "BCM",
            Venkatapuram: "Venkatapuram",
            vpm: "vpm",
        },
        Status: {
            "New": "New",
            "Created": "Created"
        },
        Braintree: {
            environment: 'braintree.Environment.Sandbox',
            merchantId: 'q577ct9g9qyq8jt7',
            publicKey: 'bdgysbrrb98f7kb7',
            privateKey: '11568834eefc8a3448a59ac682a34a63',
        },
        ImageBlob: {
            APIURL: "https://api.imgbb.com/1/upload",
            KEY: "9b568bf6699a4ee6502356e0797c48b1"
        }
    }
};