CREATE TABLE [dbo].[Doctor]
(
	[DoctorId]          UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [HospitalId]        UNIQUEIDENTIFIER  NULL,
    [StaffId]           UNIQUEIDENTIFIER  NULL,
    [SpecializationId]  UNIQUEIDENTIFIER  NULL,
    [DepartmentId]      UNIQUEIDENTIFIER  NULL,
    [RoleId]            UNIQUEIDENTIFIER  NULL,
    [FullName]          VARCHAR(100)  NULL,
    [Description]       VARCHAR(Max) NULL,
    [Experience]        VARCHAR(100) NULL,
    [Education]         VARCHAR(Max)  NULL,
    [Awards]            VARCHAR(Max)  NULL,
    [ProfileUrl]        VARCHAR(255) NULL,
    [PhoneNumber]       VARCHAR(20) NULL,
    [Email]             VARCHAR(100) NULL,
    [Address]           VARCHAR(255) NULL,
    [DateOfBirth]       DATETIMEOFFSET NULL,
    [Gender]            VARCHAR(10) NULL,
    [JoiningDate]       DATETIMEOFFSET NULL,
    [Status]            VARCHAR(50) NULL,
    [CreatedBy]                                 UNIQUEIDENTIFIER NULL,
    [CreatedOn]                                 DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    [ModifiedBy]                                UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                                DATETIMEOFFSET NULL,
    [IsActive]                                  BIT DEFAULT 1,
    CONSTRAINT FK_DoctorRegistration_Hospital FOREIGN KEY (HospitalId) REFERENCES [dbo].[Hospital](HospitalId),
    CONSTRAINT FK_DoctorRegistration_Specialization FOREIGN KEY (SpecializationId) REFERENCES [dbo].[Specialization](SpecializationId),
    CONSTRAINT FK_DoctorRegistration_Department FOREIGN KEY (DepartmentId) REFERENCES [dbo].[Department](DepartmentId),
    CONSTRAINT FK_DoctorRegistration_Role FOREIGN KEY (RoleId) REFERENCES [dbo].[Role](RoleId)
)
